### ISSUE TITLE
python3 not supported yet

### ISSUE THREAD

**Issue by ZhangZhida** [chenpengcheng/cli#11]
After installation, running leetcode-cli would give the following error. 

Traceback (most recent call last):
  File "/Users/******/miniconda3/bin/leetcode-cli", line 11, in <module>
    load_entry_point('leetcode-cli==0.0.6', 'console_scripts', 'leetcode-cli')()
  File "/Users/******/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/******/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/******/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/******/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/******/miniconda3/lib/python3.7/site-packages/leetcode_cli-0.0.6-py3.7.egg/leetcodecli/cli.py", line 266
    print 'Welcome %s!' % username
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Welcome %s!' % username)?

**Comment by ZhangZhida** [comment]
One solution is to use anaconda to create a virtual environment using python version 2.7.

**Comment by blockchainian** [comment]
@ZhangZhida thanks for flagging it. i just upgraded the code to python 3.
