### ISSUE TITLE
CSRF issue

### ISSUE THREAD

**Issue by dufferzafar** [chenpengcheng/cli#7]
When I try to login:

```
Traceback (most recent call last):
  File "/home/dufferzafar/.local/bin/leetcode-cli", line 11, in <module>
    sys.exit(main())
  File "/home/dufferzafar/.local/venvs/leetcode-cli/lib/python2.7/site-packages/leetcodecli/cli.py", line 1044, in main
    shell.do_login()
  File "/home/dufferzafar/.local/venvs/leetcode-cli/lib/python2.7/site-packages/leetcodecli/cli.py", line 764, in do_login
    self.login()
  File "/home/dufferzafar/.local/venvs/leetcode-cli/lib/python2.7/site-packages/leetcodecli/cli.py", line 266, in login
    'csrfmiddlewaretoken': csrf
UnboundLocalError: local variable 'csrf' referenced before assignment
```

**Comment by blockchainian** [comment]
@dufferzafar The issue is fixed now. :)
